name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted  # Must be a machine where Minikube is installed

    steps:
    - uses: actions/checkout@v4

    - name: Set image tag with timestamp
      id: tag
      run: |
        $unixTimestamp = [int](Get-Date -UFormat %s)
        "IMAGE_TAG=$unixTimestamp" >> $env:GITHUB_ENV

    - name: Point Docker CLI to Minikube's Docker daemon
      run: |
        minikube docker-env --shell powershell | Invoke-Expression

    - name: Build Docker image inside Minikube
      run: |
        docker build . --file Dockerfile --tag "my-image-name:${{ env.IMAGE_TAG }}"
      env:
        IMAGE_TAG: ${{ env.IMAGE_TAG }}

    - name: List images in Minikube (for verification)
      run: |
        docker images
