name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set image tag with timestamp
      id: tag
      run: |
        $unixTimestamp = [int](Get-Date -UFormat %s)
        echo "IMAGE_TAG=$unixTimestamp" >> $env:GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "my-image-name:${{ env.IMAGE_TAG }}"
      env:
        IMAGE_TAG: ${{ env.IMAGE_TAG }}

    - name: Tag image for local registry
      run: |
        docker tag my-image-name:${{ env.IMAGE_TAG }} 192.168.49.1:8082/my-image-name:${{ env.IMAGE_TAG }}

    - name: Push image to local registry
      run: |
        docker push 192.168.49.1:8082/my-image-name:${{ env.IMAGE_TAG }}
